// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitMission(name string) Mission {
	warrior := NewWarrior(name)
	monster := NewMonster()
	mission := NewMission(warrior, monster)
	return mission
}
